### ISSUE TITLE
Flame Imbued & Frost Imbued are not available on axes.

### ISSUE THREAD

**Issue by LunarNox** [MDouglas345/Brok-n-Sindri-s-Trinkets#7]
although defined with a flametool and frosttool in /enchant, they cannot be applied to any tools(I tried axes and pickaxes, abut assumed it applied to all tools) , and are functionally the same as /enchants frostweapon and flameweapon. please fix this.

**Comment by MDouglas345** [comment]
Thank you for reporting this!

I implemented the fix for frost and flame not being able to go on tools such as pickaxes and shovels. 
If you are able to build, please confirm that the 1.19 branch fixes the issue! If not, Ill test on both 1.18 and 1.19 to confirm and publish

**Comment by MDouglas345** [comment]
Believe this is now resolved, if not let me know! Thank you
